dtype_candidates = {
    "orden_candidato": "int32",
    "numero_sorteo": "int16",
    "codigo_departamento": "string",
    "nombre_departamento": "string",
    "codigo_municipio": "string",
    "nombre_municipio": "string",
    "codigo_corporacion": "int8",
    "nombre_corporacion": "string",
    "codigo_circunscripcion": "int8",
    "nombre_circunscripcion": "string",
    "opcion_voto": "int8",
    "tipo_aval": "int8",
    "codigo_partido": "string",
    "nombre_partido": "string",
    "codigo_comuna": "string",
    "nombre_comuna": "string",
    "numero_candidato": "int16",
    "numero_identificacion": "string",
    "primer_nombre": "string",
    "segundo_nombre": "string",
    "primer_apellido": "string",
    "segundo_apellido": "string",
    "genero_candidato": "string",
    "letra_partido": "string",
    "estado_lista": "string",
    "marca_candidato": "string"
}
    